import { Subject, Faculty, PeriodInfo, Room } from './types';

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'CNS', name: 'CNS', hoursPerWeek: 5, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'SE', name: 'SE', hoursPerWeek: 5, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'PDC', name: 'PDC', hoursPerWeek: 5, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'CSA', name: 'CSA', hoursPerWeek: 5, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'DL', name: 'DL', hoursPerWeek: 5, sections: [1, 8], isLabOrTutorial: false },
  { id: 'ML', name: 'ML', hoursPerWeek: 5, sections: [2, 10, 11, 12, 13, 14], isLabOrTutorial: false },
  { id: 'ADS', name: 'ADS', hoursPerWeek: 5, sections: [3, 4, 5, 6], isLabOrTutorial: false },
  { id: 'AJP', name: 'AJP', hoursPerWeek: 5, sections: [7], isLabOrTutorial: false },
  { id: 'DIP', name: 'DIP', hoursPerWeek: 5, sections: [9], isLabOrTutorial: false },
  { id: 'MAD', name: 'MAD', hoursPerWeek: 5, sections: [15, 16, 17, 18, 19], isLabOrTutorial: false },
  { id: 'IDP', name: 'IDP', hoursPerWeek: 3, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'QLR', name: 'QLR/QALR', hoursPerWeek: 3, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'OE', name: 'OE', hoursPerWeek: 3, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
  { id: 'CNS-L', name: 'CNS-L', hoursPerWeek: 2, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: true },
  { id: 'SE-L', name: 'SE-L', hoursPerWeek: 2, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: true },
  { id: 'CSA-L', name: 'CSA-L', hoursPerWeek: 2, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: true },
  { id: 'PDC-T', name: 'PDC-T', hoursPerWeek: 2, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: true },
  { id: 'TRAINING', name: 'Training', hoursPerWeek: 6, sections: Array.from({ length: 19 }, (_, i) => i + 1), isLabOrTutorial: false },
];

export const INITIAL_FACULTY: Faculty[] = [
  { id: 'F1', name: 'Dr. Vinoj J', subjects: ['SE', 'SE-L'], allottedSections: [1, 2, 11, 4, 15] },
  { id: 'F2', name: 'Dr. S V Phani Kumar', subjects: ['DL'], allottedSections: [1, 8] },
  { id: 'F3', name: 'Dr. P. Siva Prasad', subjects: ['CNS'], allottedSections: [1, 11, 15, 16] },
  { id: 'F4', name: 'Mr Kiran Kumar Kaveti', subjects: ['CNS', 'CNS-L'], allottedSections: [1, 9, 12, 16, 18] },
  { id: 'F5', name: 'Ms Swarna Lalitha', subjects: ['IDP'], allottedSections: [1, 13, 17, 19, 2, 3] },
  { id: 'F6', name: 'Ms Sai Spandana', subjects: ['IDP', 'PDC'], allottedSections: [1, 5, 19, 10, 11] },
  { id: 'F7', name: 'Dr. M. Sunil Babu', subjects: ['PDC', 'IDP'], allottedSections: [1, 4, 5, 11, 14, 15] },
  { id: 'F8', name: 'Dr T.R. Rajesh', subjects: ['SE-L', 'SE'], allottedSections: [1, 2, 12, 13, 17] },
  { id: 'F9', name: 'Ms D. Manogna', subjects: ['CSA', 'CSA-L'], allottedSections: [1, 2, 3, 4, 5] },
  { id: 'F10', name: 'Mr Syed Nafees', subjects: ['CSA', 'CSA-L'], allottedSections: [1, 12, 13, 14, 15] },
  { id: 'F11', name: 'Ms. Sd. Shareefunnisa', subjects: ['PDC', 'IDP'], allottedSections: [2, 16, 17, 18] },
  { id: 'F12', name: 'Dr. Jhansi Lakshmi P', subjects: ['ML'], allottedSections: [2, 12, 10, 11] },
  { id: 'F13', name: 'Dr. Prashant Upadhyay', subjects: ['CNS'], allottedSections: [2, 18, 19, 5] },
  { id: 'F14', name: 'Dr G. Parimala', subjects: ['CNS-L', 'CNS'], allottedSections: [2, 3, 6, 14, 10] },
  { id: 'F15', name: 'Ms N. Sarvani', subjects: ['CNS-L', 'CNS'], allottedSections: [2, 4, 8, 17, 12] },
  { id: 'F16', name: 'Ms Leelavathy', subjects: ['IDP', 'PDC'], allottedSections: [2, 6, 9, 18, 13] },
  { id: 'F17', name: 'Ms Priya Bharathi', subjects: ['CSA', 'CSA-L'], allottedSections: [2, 3, 7, 10, 19] },
  { id: 'F18', name: 'Mr Raj Kiran', subjects: ['CSA', 'CSA-L'], allottedSections: [2, 13, 11, 16] },
  { id: 'F19', name: 'Mr. S. Suresh Babu', subjects: ['ADS'], allottedSections: [3, 5, 6] },
  { id: 'F20', name: 'Mr Brahma Naidu', subjects: ['ADS', 'ADS-T'], allottedSections: [3, 4, 6] },
  { id: 'F21', name: 'Dr. Bh. Krishna Reddy', subjects: ['CNS'], allottedSections: [3, 19, 7, 8] },
  { id: 'F22', name: 'Ms. Shaik Reehana', subjects: ['IDP', 'PDC'], allottedSections: [3, 6, 7, 12, 14] },
  { id: 'F23', name: 'Dr Prathap Kumar', subjects: ['IDP'], allottedSections: [3, 4, 15, 16] },
  { id: 'F24', name: 'Mr. K. Pavan Kumar', subjects: ['PDC', 'IDP'], allottedSections: [3, 15, 18, 9, 10] },
  { id: 'F25', name: 'Mr. N. Uttej Kumar', subjects: ['SE', 'SE-L'], allottedSections: [3, 8, 9, 13, 19] },
  { id: 'F26', name: 'Ms Sajida Sultana', subjects: ['SE-L', 'SE'], allottedSections: [3, 4, 6, 10, 18] },
  { id: 'F27', name: 'Mr R. Gowtham', subjects: ['CSA', 'CSA-L'], allottedSections: [3, 16, 17, 8, 9] },
  { id: 'F28', name: 'Ms R. Nithya', subjects: ['CSA', 'CSA-L'], allottedSections: [3, 5, 11, 17, 6] },
  { id: 'F29', name: 'Dr. J. Vijitha Ananthi', subjects: ['CNS'], allottedSections: [4, 17, 1] },
  { id: 'F30', name: 'Mr Sk Jani', subjects: ['IDP', 'PDC'], allottedSections: [4, 10, 13, 2, 7] },
  { id: 'F31', name: 'Mr. P. Vijaya Babu', subjects: ['PDC'], allottedSections: [4, 9, 14, 18] },
  { id: 'F32', name: 'Mr U. Venkateswara Rao', subjects: ['SE-L'], allottedSections: [4, 12, 13, 14, 17, 1, 2] },
  { id: 'F33', name: 'Mr. Sd. Nafees Ahamed', subjects: ['CSA', 'CSA-L'], allottedSections: [4, 9, 10] },
  { id: 'F34', name: 'Dr. James Deva Koresh H', subjects: ['CNS', 'IDP'], allottedSections: [5, 12, 15, 16, 19, 3] },
  { id: 'F35', name: 'Ms V. Anusha', subjects: ['CNS-L', 'CNS'], allottedSections: [5, 8, 10, 13, 14, 19] },
  { id: 'F36', name: 'Mrs. V. Nandini', subjects: ['SE', 'SE-L'], allottedSections: [5, 13, 19, 7, 8] },
  { id: 'F37', name: 'Ms B. Maneesha', subjects: ['CSA', 'CSA-L'], allottedSections: [5, 12, 17, 18, 14] },
  { id: 'F38', name: 'Mr. Mohan Venkateswara Rao', subjects: ['SE', 'SE-L'], allottedSections: [6, 10, 11, 18, 16] },
  { id: 'F39', name: 'Mr. Chand', subjects: ['QLR'], allottedSections: Array.from({ length: 10 }, (_, i) => i + 1) },
  { id: 'F40', name: 'Mr. Chavva Ravi Kishore Reddy', subjects: ['AJP'], allottedSections: [7] },
  { id: 'F41', name: 'Ms. M. Bhargavi', subjects: ['CNS'], allottedSections: [7, 15, 18, 4] },
  { id: 'F42', name: 'Mr K. Harish', subjects: ['PDC'], allottedSections: [7, 6, 8] },
  { id: 'F43', name: 'Mr. T Narasimha Rao', subjects: ['SE', 'SE-L'], allottedSections: [7, 15, 16, 17] },
  { id: 'F44', name: 'Ms Kollabathula Nimnagasri', subjects: ['CSA', 'CSA-L'], allottedSections: [7, 15, 16, 1] },
  { id: 'F45', name: 'Mr Aditya Venkateswara Kumar', subjects: ['CSA', 'CSA-L'], allottedSections: [7, 15, 18, 19] },
  { id: 'F46', name: 'Dr. B. Suvarna', subjects: ['DL', 'IDP'], allottedSections: [8, 1, 2] },
  { id: 'F47', name: 'Ms. Tanigundala Leelavathy', subjects: ['PDC'], allottedSections: [8, 18, 19] },
  { id: 'F48', name: 'Mr. Kumar Devapogu', subjects: ['SE', 'SE-L'], allottedSections: [8, 16, 11] },
  { id: 'F49', name: 'Dr K. RAMBABU', subjects: ['DIP'], allottedSections: [9] },
  { id: 'F50', name: 'Mr. E. Akhil Babu', subjects: ['PDC', 'IDP'], allottedSections: [9, 12, 16, 17, 5] },
  { id: 'F51', name: 'Ms. K. Jyostna', subjects: ['SE', 'SE-L'], allottedSections: [9, 17, 12, 13] },
  { id: 'F52', name: 'Ms A. Durga Bhavani', subjects: ['CSA', 'CSA-L'], allottedSections: [9, 11, 12] },
  { id: 'F53', name: 'Dr. S. Deva Kumar', subjects: ['ML'], allottedSections: [10, 13, 14] },
  { id: 'F54', name: 'Mr. Sourav Mondal', subjects: ['ML'], allottedSections: [11, 14, 10] },
  { id: 'F55', name: 'Dr. E. Deepak Chowdary', subjects: ['MAD', 'MAD-T'], allottedSections: [15, 18, 19] },
  { id: 'F56', name: 'Mrs. J. Dayanika', subjects: ['MAD', 'MAD-T'], allottedSections: [16, 19, 15, 17] },
  { id: 'F57', name: 'Ms G. Tejaswi', subjects: ['MAD-T'], allottedSections: [16, 17, 18, 19] },
  { id: 'F58', name: 'MR TS QLR', subjects: ['QLR'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
  { id: 'F59', name: 'MT MW QLR', subjects: ['QLR'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
  { id: 'F60', name: 'MR J Naresh QLR', subjects: ['QLR'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
  { id: 'F61', name: 'MR. KIRAN KUMAR', subjects: ['QLR'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
  { id: 'F62', name: 'OE DEPT', subjects: ['OE'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
  { id: 'PDC_DEPT', name: 'PDC Dept', subjects: ['PDC-T'], allottedSections: Array.from({ length: 19 }, (_, i) => i + 1) },
];

export const INITIAL_ROOMS: Room[] = [
  { id: '301', capacity: 70, type: 'LAB' },
  { id: '304', capacity: 70, type: 'LAB' },
  { id: '305', capacity: 70, type: 'LAB' },
  { id: '306', capacity: 70, type: 'LAB' },
  { id: '307', capacity: 70, type: 'LAB' },
  { id: '308', capacity: 70, type: 'LAB' },
  { id: '309', capacity: 70, type: 'LAB' },
  { id: '310', capacity: 70, type: 'LAB' },
  { id: '311', capacity: 70, type: 'LAB' },
  { id: '312', capacity: 70, type: 'LAB' },
  { id: '313', capacity: 70, type: 'LAB' },
  { id: '314', capacity: 70, type: 'LAB' },
  { id: '315', capacity: 70, type: 'LAB' },
  { id: '316', capacity: 70, type: 'LAB' },
  { id: '317', capacity: 70, type: 'LAB' },
  { id: '318', capacity: 70, type: 'LAB' },
  { id: '319', capacity: 70, type: 'THEORY' },
  { id: '401', capacity: 70, type: 'LAB' },
  { id: '404', capacity: 70, type: 'LAB' },
  { id: '405', capacity: 70, type: 'LAB' },
  { id: '406', capacity: 70, type: 'LAB' },
  { id: '407', capacity: 70, type: 'LAB' },
  { id: '408', capacity: 70, type: 'LAB' },
  { id: '410', capacity: 70, type: 'LAB' },
  { id: '411', capacity: 70, type: 'LAB' },
  { id: '412', capacity: 70, type: 'LAB' },
  { id: '413', capacity: 70, type: 'LAB' },
  { id: '414', capacity: 70, type: 'LAB' },
  { id: '415', capacity: 70, type: 'LAB' },
  { id: '416', capacity: 70, type: 'LAB' },
  { id: '417', capacity: 70, type: 'LAB' },
  { id: '418', capacity: 70, type: 'LAB' },
  { id: '419', capacity: 70, type: 'THEORY' },
];

export const PERIODS: PeriodInfo[] = [
  { no: 1, time: '8:15-9:05', type: 'Teaching' },
  { no: 2, time: '9:05-9:55', type: 'Teaching' },
  { no: 3, time: '10:10-11:00', type: 'Teaching' },
  { no: 4, time: '11:00-11:50', type: 'Teaching' },
  { no: 5, time: '11:50-12:40', type: 'Teaching' },
  { no: 6, time: '13:40-14:30', type: 'Teaching' },
  { no: 7, time: '14:30-15:20', type: 'Teaching' },
  { no: 8, time: '15:20-16:05', type: 'Teaching' },
];
